general:
  output_dir: "dist"
  site_name: "Yew SSG Example"
  default_image: "/images/default-social-cover.jpg"
  template_path: "dist/index.html"
  assets_base_dir: "assets"
  canonical_to_default_langs: false
  default_language: "en"

global_metadata:
  keywords: "yew, rust, ssg, webdev, spa, seo"
  charset: "utf-8"
  viewport: "width=device-width, initial-scale=1.0"
  og:type: "website"
  alternate_languages: "en,es,de"
  domain: "https://example.com"

  # Organization JSON-LD data (used across the site)
  organization_name: "Yew SSG Project"
  organization_logo: "https://example.com/logo.png"
  organization_type: "SoftwareApplication"
  organization_url: "https://example.com"
  organization_founder: "The Yew SSG Team"
  organization_founding_date: "2025-04-01"

routes:
  - path: "/"
    metadata:
      title: "Home | Yew SSG Example"
      description: "Welcome to the Yew Static Site Generator example homepage. See how Yew SPAs can be SEO-friendly."

      json_ld_type: "WebSite"
      headline: "Yew SSG - Static Site Generation for Rust Web Apps"
      publisher: "Yew SSG Project"
      author: "Yew SSG Team"
      date_published: "2025-02-15"
      date_modified: "2025-03-10"

  - path: "/en/"
    metadata:
      title: "Home | Yew SSG Example (English)"
      description: "Welcome to the Yew Static Site Generator example homepage in English."
      lang: "en"
      canonical: "https://example.com/"
      alternate_url_en: "https://example.com/?lang=en"
      alternate_url_es: "https://example.com/es/"

  - path: "/de/"
    metadata:
      title: "Startseite | Yew SSG Beispiel (Deutsch)"
      description: "Willkommen auf der Yew Static Site Generator Beispielseite in Deutsch."
      lang: "de"

  - path: "/about"
    metadata:
      title: "About Us | Yew SSG Example"
      description: "Learn about the yew-ssg project and how it helps pre-render Yew applications."

  - path: "/readme"
    metadata:
      title: "README | Yew SSG Documentation"
      description: "Explore the documentation and usage examples for yew-ssg static site generation."

  - path: "/404"
    metadata:
      title: "Page Not Found (404) | Yew SSG Example"
      description: "Oops! The page you are looking for doesn't exist. Please check the URL."
      robots: "noindex, nofollow"

parameterized_routes:
  - pattern: "/crate/:id"
    parameters:
      - name: "id"
        values: ["yew-ssg", "yew-ssg-router"]
    metadata:
      section: "Crates"
    variants:
      - values:
          id: "yew-ssg"
        metadata:
          title: "yew-ssg | Static Site Generator for Yew"
          description: "A powerful static site generator that pre-renders Yew applications into SEO-friendly HTML."
          keywords: "yew, rust, ssg, static site generator, seo"
          json_ld_file: "yew-ssg.jsonld"

      - values:
          id: "yew-ssg-router"
        metadata:
          title: "yew-ssg-router | Router Integration for Yew SSG"
          description: "Router integration for yew-ssg that provides static pre-rendering with client-side navigation."
          keywords: "yew, rust, router, ssg, static site generator"
